### ISSUE TITLE
hash_map infinite recursive loop

### ISSUE THREAD

**Issue by Gpinchon** [FrozenStormInteractive/Crunch2#1]
operator != calls operator !=, thuse resulting in an infinite recursive loop, maybe you meant `return !(*this == b)`
https://github.com/FrozenStormInteractive/Crunch2/blob/2b7f79adc0dc1a2cfd42d764191dcf2044fe97da/crnlib/crn_hash_map.h#L345

**Comment by intelligide** [comment]
I have fixed the bug for quite some time but I had not done a release. The fix is available in 1.3.1.

I'll try to find some time to write some tests and consolidate the code.
